spring:
  application:
    name: fortune-gateway
  cloud:
    gateway:
      routes:
      - id: fortune_teller_ui
        uri: http://fortune-ui
        predicates:
        - Path=/**
      - id: fortune_teller_api
        uri: http://fortune-service
        predicates:
        - Path=/api/**
        filters:
        - RewritePath=/stocks/(?<path>.*), /$\{path}

---
spring:
  profiles: cloud
server:
  port: ${vcap.application.port:8080}
