service_name: fortunes-config-server
service: p-config-server
service_plan: trial
parameters:
  git:
    uri: https://github.com/msathe-tech/fortune-teller
    searchPaths: configuration
---
service_name: fortunes-service-registry
service: p-service-registry
service_plan: trial
---
service_name: fortunes-circuit-breaker-dashboard
service: p-circuit-breaker-dashboard
service_plan: trial
---
service_name: fortunes-db
service: cleardb
service_plan: spark
